# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkADBFileBrowserWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 731)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/res/ft_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tree_a = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        self.tree_a.setAcceptDrops(False)
        self.tree_a.setDragEnabled(False)
        self.tree_a.setDragDropOverwriteMode(False)
        self.tree_a.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tree_a.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_a.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tree_a.setUniformRowHeights(False)
        self.tree_a.setWordWrap(False)
        self.tree_a.setObjectName("tree_a")
        self.verticalLayout.addWidget(self.tree_a)
        self.tb_info = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_info.sizePolicy().hasHeightForWidth())
        self.tb_info.setSizePolicy(sizePolicy)
        self.tb_info.setMaximumSize(QtCore.QSize(16777215, 120))
        self.tb_info.setObjectName("tb_info")
        self.verticalLayout.addWidget(self.tb_info)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "文件删除等请谨慎操作！！！"))
        self.tree_a.setSortingEnabled(False)
        self.tree_a.headerItem().setText(0, _translate("MainWindow", "目录"))
import linkadb_file_browser_rc
